/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

//importaciones para webdriver
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.chrome.ChromeOptions;

//anotaciones para testng
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import org.testng.annotations.BeforeMethod;

import org.openqa.selenium.*;
import org.openqa.selenium.io.FileHandler;
import java.io.File;
import java.time.Duration;
import java.io.IOException;


public class AppTest {
    WebDriver driver;
    WebDriverWait wait;

    @BeforeClass
    public void initSetup () {
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--remote-allow-origins=*");
        options.addArguments("--disable-gpu");
        options.addArguments("--no-sandbox");
        options.addArguments("--disable-dev-shm-usage");
        options.addArguments("--disable-blink-features=AutomationControlled");
        options.addArguments("--disable-features=NetworkService,NetworkServiceInProcess");

        WebDriverManager.chromedriver().clearDriverCache().setup();
        driver = new ChromeDriver(options);
        driver.manage().window().maximize();
        //Espera global
        wait = new WebDriverWait(driver, Duration.ofSeconds(5));
        //Espera especifica
        wait = new WebDriverWait(driver, Duration.ofSeconds(5));
    }

    @Test
    public void OpenNav () throws IOException, InterruptedException {
        //abrir el navegador en la dirección indicada
        driver.get("https://www.google.com");
        //Se debe obtener el identificador del frame
        String mainWindowHadle = driver.getWindowHandle();


    }
}
